### ISSUE TITLE
When I run  example_simple_experiment.m file, there occurred a  series of problems.

### ISSUE THREAD

**Issue by zhengyi0533** [volcic/motom-toolbox#10]
Hi! 
You foreseed the problem. Are there too many problems to be solved? Thank you for taking the time to answer my questions.

Warning: The data type 'error#32' used by structure OptoNodeInfoStruct does not exist.  The structure may not be
usable. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'error#256' used by structure AlignParametersStruct does not exist.  The structure may not be
usable. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'error#256' used by structure RegisterParametersStruct does not exist.  The structure may not
be usable. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'error#256' used by structure CalibrigParametersStruct does not exist.  The structure may not
be usable. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The function 'ReadAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The function 'ReadAppParms_d' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The function 'SaveAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The function 'SaveAppParms_d' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The function 'DeleteAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'FcnPtr' used by function OAPIDetermineR does not exist. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'FcnPtr' used by function OAPITransformPoint does not exist. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'FcnPtr' used by function DetermineR does not exist. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
Warning: The data type 'FcnPtr' used by function TransformPoint does not exist. 
> In loadlibrary
  In optotrak_startup (line 30)
  In example_simple_experiment (line 20) 
The optotrak system says: OAPI version check failed on node 0 : fw 3.19  oapi 3.5
Error using optotrak_startup (line 60)
TransputerInitializeSystem failed. Something must have gone very wrong with the initialisation.

Error in example_simple_experiment (line 20)
optotrak_startup;

**Comment by ha5dzs** [comment]
Now this is interesting.

You can ignore the `loadlibrary` warnings, I have been getting these even with the latest OAPI, this happens because the variable types have been extracted automatically, and since NDI put the OAPI headers together by copying and pasting a bunch of internal header files together, there are some double declarations. For example `FcnPtr` is just `void *`, and so on.

...and this is the interesting bit:
```
The optotrak system says: OAPI version check failed on node 0 : fw 3.19 oapi 3.5
```
This is the output of `optotrak_tell_me_what_went_wrong()`, there might be something more in `OPTO.ERR`. It seems that `TransputerDetermineSystemCfg()` failed, which is the very first OAPI function you call to initialise the system.
`TransputerDetermineSystemCfg()` did find your SCU, and it seems that it has a relatively recent (3.19) firmware. We have two SCUs in the lab, which -before the upgrade that broke compatibility with the older 3020 cameras- did have the firmware 3.19 and 3.12 respectively. They were bought only a couple of years ago, so you if your SCU is not new, it must have been upgraded before.

I think `TransputerDetermineSystemCfg()` failed, because it checked the versions of both the SCU firmware and your OAPI version, and they don't seem to be compatible for some reason. This comes from within the OAPI binaries, you can't control it externally.

Can you tell me about your set-up, and can you tell me why you can't contact NDI for a newer version of OAPI?

**Comment by zhengyi0533** [comment]
Thank you for your analysis and answer to the question. I borrowed someone else's equipment, and I told him about the API upgrade. This may take some time. Do we only need to email NDI to upgrade API? I'm not sure what set-up means. I paste the content of the example_simple_config_file.ini file here. The sensor's model is Optotrak Certus Position and the SCU's model is Optotrak System Control Unit. 

[OPTOTRAK System]
NumberOfMarkers = 4
FrameFrequency = 10
MarkerFrequency = 1000
DutyCycle = 0.68
StroberVoltage = 7
InterpolationFlag = TRUE
NoFireMarkers = FALSE
StaticThresholdFlag = FALSE
StaticThresholdValue = 0
DynamicThresholdPercent = 30
MinimumGain = 160
CollectionTime = 30
PreTriggerTime = 0
StreamData = 1
DynamicDutyFlag = FALSE
BufferWaveformsFlag = FALSE
Buffer3dFlag = FALSE
BufferFullRawFlag = FALSE
GetNextFrameFlag = FALSE
ExternalSyncFlag = FALSE
ExternalTriggerFlag = FALSE
PollRealDataFlag = FALSE
bConvertOnHost = TRUE
bRigidOnHost = TRUE
MarkerType = 3
WavelengthType = 0
ModelType = 1
TimeOut = 5
bIgnoreVersionCheck = FALSE
bPerformExpectedSystemCheck = FALSE
bmode = 0
RCParam1 = 0
RCParam2 = 1
3dErrorMode = 1

**Comment by ha5dzs** [comment]
Yes, send them an email, they should reply soon.

My question was about your hardware configuration. Now I know that you have a Certus system. You are not using an Optotrak 3020 camera with your Certus, right?

**Comment by zhengyi0533** [comment]
Yes, I only have an Optotrak Certus.

**Comment by ha5dzs** [comment]
Okay, then as soon as you get the recent API files, everything should work normally.
