### ISSUE TITLE
The number of frames in the system initialisation do not match with the number of frames in the data file!

### ISSUE THREAD

**Issue by zhengyi0533** [volcic/motom-toolbox#13]
Hi!
When I collected data, the program suddenly reported an error（The number of frames in the system initialisation do not match with the number of frames in the data file!）, but before that, no exception was displayed. Most of this happens after the program has been running for a long time.Do you know what's wrong with this?
Thanks!

**Comment by ha5dzs** [comment]
Based on the error message this comes from either `optotrak_convert_raw_file_to_position3d_array()` or `optotrak_convert_raw_file_to_rigid_euler_array()`.

This error message is produced from the C-code that does the conversion of a raw data file to something Matlab can work with. The conversion itself not only can take place with a properly initialised system, BUT, the raw data file has to be processed with the same data acquisition settings: the number of markers, cameras, frame frequency, data collection time, all have to be the same. You can load a different camera file though.

At first I thought this is some simple variable overflow problem, but since I initialised these variables as `long`, and `FileOpen()` also writes into the `number_of_frames` variable as `long`, overflow would only occur when you when you have some ridiculously long data files (like 2 billion frames or so).

Now to investigate this further, can you tell me about how you are using this function?
Are you using the same config file to convert the raw data as you were creating them with?
Also, can you tell me about your data acquisition settings? (number of markers, frame frequency, and collection time)

**Comment by zhengyi0533** [comment]
Sorry，I asked a stupid question.Last year, due to the placement of the sensor, some  trials could not record data, which was deleted during the operation of the program. At that time, I modified the example code when to stop data collection for each trial. Now the sensor does not lose data. The code for deleting the trial was deleted, but I forgot to modify other places, which led to this error. Thanks！
