### ISSUE TITLE
Frame Frequency vs. Marker Frequency

### ISSUE THREAD

**Issue by MfMartel** [volcic/motom-toolbox#3]
Hi,

I am struggling to understand how frame frequency and marker frequency are related. I have tried several values and sometimes the system can not be initiated, and some other times it works and I get the data.

From what I understand, the marker frequency is the one you also specify on NDI, depending on the number of markers you have, and obtained with the formula (frequency = 4600/(n+2.3)).
For my experiment, I put 250Hz. This means that I have one flash of marker every 4ms.

But what is the frame frequency then? I realised that frame frequency * collection time gives you the number of frames of your trials. This means that with a frame frequency of 50Hz (the one you often put in the example scripts), you get one data point every 20ms. And you get for instance 500 frames for a 10sec-long trial.

How do these 2 values reconcile? Is the value for each 20ms, the mean of the 5 points you get (one each 4ms)? Is a random point selected within these 5?

Finally, how do we know the maximum frame frequency you can put without preventing the initialisation.

Thank you for your help!

**Comment by ha5dzs** [comment]
Yep, this is a weird thing and I think this could have been written clearer in the documentation.

So, within each frame, all the markers are flashed sequentially, one after an other. At the end of the frame, there has to be some extra time for the flashing sequence to be restarted (that's the n+2 in the formula, but it's different for the Certus and 3020 systems, and whether you are using wireless markers, and even the firmware version within the same system: for my configuration is actually 1.7, but yours might be different).

So if you use the Certus system, and have 10 markers, and you want to sample at the frame frequency of 50Hz, the marker frequency need to be between 4600Hz and ((10+2)*50)= 600 Hz.

For a 10 second buffer, the system will return 500 frames, irrespective of what marker frequency you set, as long as they are between these two values. This is because the sequential flashing can be done quicker than the frame duration. If the system executed the marker flashing sequence before the duration of a frame, it just simply waits until the next frame. There might be applications where short flashes are required combined with a low frame rate. Kinda like playing with the exposition time in photography.

Let's say that you decide to set the marker frequency to be 1kHz. This means that each marker has a time slot of 1 ms, but the actual duration of the markers being flashed is smaller than this: within the 1 ms time slot, if you have a marker duty cycle of 60%, the marker is only being lit for ((1/1000Hz)*0.6) = 600 microseconds.


From this, it might seem that keeping up the marker frequency at 4600Hz all the time is a good option. Unfortunately this is not the case.

So, let's say that you decide to put the marker frequency at 4600Hz, and the duty cycle of 50%. This means that a marker is lit (1(/4600)*0.5) = 109 microseconds. Now since this is a LED flash, the marker will be flashed with a square wave signal. For a square wave signal to propagate over a transmission line (which is in this case the twisted pair wire from the strober to the marker itself), we need to let at least the first five harmonics to propagate too: For the marker, the base harmonic is (1/109E-6) 9200Hz, and its fifth-seventh harmonic is about 46KHz, so we can estimate a bandwidth of 50-70 kHz. At these frequencies, the way you handle the wire will play a role: for example if you spool it up, you are creating an inductor, and if you drive an inductor with a square wave, two things will happen:
1., There will be a noticeable delay at the onset time of the flash  
2., At the offset of the flash, there will be a negative voltage transient produced by the inductor  
This will lead to bad tracking accuracy and over-heating (and damaged) markers.

Setting the marker frequency to be the lowest possible is also not a good option: Since the Certus system calculates the timing required based on its own clock source, it will not always be able to sample at the frame rate you have set. For example, when my system was set for 200 frames per second, it returns 200.00771 frames per second. You can check this by corresponding the output of `optotrak_get_setup_info()` with the frame rate you set in the config file. Since this timing may be slightly smaller or larger than the frame rate you set, it can happen that the system initialisation will fail because it thinks there isn't enough time to flash all the markers.


So I usually use the marker frequency of the lower quarter of the interval given by the number of markers and the required frame frequency. For the example given above, I would use the marker frequency of 1000Hz.

**Comment by MfMartel** [comment]
I see! Thanks for the clarification, it makes more sense now. I think I actually had mistaken the 2 frequencies... For me, with 10 markers, you could not put a frequency higher than (4600/(10+2)) = 380Hz per marker and I thought that this was the marker frequency in the config file. But it is in fact the frame frequency, am I right?

This means that if I have 4 markers and I want to record my data with a frequency of 250Hz (frame frequency), I can put a marker frequency inbetween ((4+2) * 250) = 1500 & 4600Hz. 
Following your lower quarter advice, I chose 2000Hz as marker frequency. It is actually a bit lower than a real quarter; does it matter or is it ok this way?

The system intialised just fine.

**Comment by ha5dzs** [comment]
Yep, that seems good to me. This 'lower quarter' thing is just my way of doing it, so 2kHz marker frequency looks fine for your 4 markers recording at 250 frames per second.
