### ISSUE TITLE
Error using loadlibrary

### ISSUE THREAD

**Issue by sciencecrazy** [volcic/motom-toolbox#8]
Hi there, I've only found this resource created by you yesterday and really thank you for the efforts you've put in to the development. 

I have a question as well regarding an error I'm getting in running the RUNME.m. I'm using a Windows 64-bit computer, with 64-bit Matlab 2018b, with OAPI v3.14.10. The error is as follows:

> Error using loadlibrary
Failed to preprocess the input file.
 Output from preprocessor is:In file included from //uofa/users$/users2/a1763222/Desktop/Optotrak
 API/motom-toolbox-master/source/ndtypes.h:7:0,
                 from \\uofa\users$\users2\a1763222\Desktop\Optotrak API\motom-toolbox-master\generated_binaries\..\source\ndopto.h:21:
//uofa/users$/users2/a1763222/Desktop/Optotrak API/motom-toolbox-master/source/ndhost.h:153:2: error: #error unknown X86 compiler
 #error unknown X86 compiler
  ^~~~~
Error in RUNME (line 104)
        [~, warnings] = loadlibrary('../bin/oapi64.dll', '../source/ndopto.h', 'addheader', '../source/ndtypes.h', 'addheader',
        '../source/ndhost.h', 'addheader', '../source/ndpack.h', 'mfilename', 'api_prototypes');

Is it an issue with the compiler being used (MinGW64 Compiler with Windows 10 SDK or later (C++)) ? 

Thanks in advance.

**Comment by ha5dzs** [comment]
Hi,

Zoltan here.

(edit: confusion about version numbers, I thought you have a newer version than mine)
Can you get the latest version of API? It is the 3.15.

It seems that the error message is generated by the header file, there are a number of `#define` directives in `ndhost.h`. It could well be that the MinGW compiler with the Windows SDK was not yet supported with that version.

If you can't get the latest OAPI, can you try installing Visual Studio with C++ support and use it as a main compiler for Matlab?

`RUNME.m` should then run fine, and all your `loadlibrary` stuff will be generated along with the `.mex` files.

**Comment by ha5dzs** [comment]
I edited the earlier post many times, please check the latest version. Sorry, covid blues! :)

**Comment by sciencecrazy** [comment]
Thanks for this Zoltan. One bad news and one good. On the computer in the lab, I changed Matlab's main compiler to be Microsoft Visual C++ 2017 as you mentioned, but that didn't solve the issue, same problem. 

Then I decided to run RUNME.m on my desk PC, which is also a 64 bit windows 10, has the same 64-bit R2018b Matlab installed, and I changed its main compiler to also be Microsoft Visual C++ 2017, and the compilation worked ! 

So works on one PC but not the other, I'm not sure why, they seem to have the same specs. Now that I have successfully compiled on one PC, can I just copy the files from my desk PC to the lab PC? And if so, which files/ folders would I need to copy?

**Comment by ha5dzs** [comment]
Answers sequentially:
> On the computer in the lab, I changed Matlab's main compiler to be Microsoft Visual C++ 2017

...and the compilation still fails? This is strange, because there are no extra dependencies required. Is the Visual Studio compiler selected in Matlab? You need to manually select it, the newly installed one doesn't get selected by default, if I remember correctly: [see here](https://www.mathworks.com/help/matlab/matlab_external/choose-c-or-c-compilers.html).

> can I just copy the files from my desk PC to the lab PC?

Theoretically yes, everything that was compiled has been saved to the folder `generated_binaries`. If you copy all the files inside, you don't need to run `RUNME.m` any more, and everything should work. You need to run `add_toolbox_to_path.m`, so the binaries are available on tap, the toolbox relies on them.
Then, you can test whether it works by typing
```
optotrak_startup;
```
...in the command window, which loads the API functions into the memory using `loadlibrary()`. The mex files are just executed as required in the code. This also calls `TransputerDetermineSystemCfg()`, and you hopefully have meaningful error messages if something is wrong from now on.

**Comment by sciencecrazy** [comment]
I just copied the 'generated_binaries' folder's contents from my desk PC to the lab PC and followed your steps and it worked ! I'm just working through some optotrak connectivity issues now, otherwise seems to be working ok.

**Comment by ha5dzs** [comment]
Cool! Still puzzled on why it didn't compile with the lab computer. If you ever find out, please let me know.

**Comment by sciencecrazy** [comment]
I'll definitely let you know if I ever find out the cause. Meanwhile, I've encountered another issue which I can't seem to fix. First Principle can connect to Optotrak, but when I run optotrak_startup, TransputerDetermineSystemCfg() fails. I'm connecting to the optotrak via the usb interface and I have the 'usblink.dll' driver in the NDI folder, not 'usblink64.dll'. I saw the Damage Control section on this issue and I changed my Optotrak.ini file to include the usb line like so: 

[TLD Info]
realtime =drealtim.tld
admin    =dadmin.tld
sensor   =dsensor.tld
oscope   =oscope2.tld

[OPTOTRAK System]
**Driver   = usblink.dll**
ResetTimeout		=1
PropagationTimeout	=0

[Strober Table]
Port1 =6
Port2 =0
Port3 =0
Port4 =0

[Ethernet Options]
Control Port=9999
Data Port=10000
Data Timeout=4000
Reset Delay=10000

And still, the TransputerDetermineSystemCfg() fails. Is it to do with the fact that I don't have the usblink64.dll driver installed and that's what the optotrak_startup script needs?

**Comment by ha5dzs** [comment]
Unfortunately First Principles is using its own library implementation, and is working with the 32-bit drivers. Since you compiled the binaries in the toolbox on a 64-bit machine, you will have to use the 64-bit drivers, the functions inside the compiled code won't work with the 32-bit drivers. They are available on Northern Digital's support website [here](support.ndigital.com) for free, if you can't access it, let me know.

Basically, the USB adapter is some form of a serial port device (FTDI-based, I think, I don't have it at home where I am working from), but they changed the driver to improve the latency on real-time data. Otherwise, your `optotrak.ini` file looks fine, just change back the `usblink.dll` to `usblink64.dll`, and make sure you copy the usblink64.dll file from the installer to where the rest of your interface DLL files are.

edit:
The Optotrak USB adapter is FTDI-based. You may also need to install a new version of the Optotrak device drivers too.

**Comment by sciencecrazy** [comment]
Hallelujah IT WORKS ! I found the 64-bit driver and put it in that directory, changed the optotrak.ini file accordingly and updated the driver for the usb interface. Matlab can now talk to Optotrak. Now to play around with the API functions and example scripts! Thanks again Zoltan for this tool and all your help.

**Comment by ha5dzs** [comment]
Cool, have fun! And please close this issue. For every five closed issues, I may get a free toaster! :)
