### ISSUE TITLE
Error using loadlibrary. Failed to preprocess the input file.

### ISSUE THREAD

**Issue by zhengyi0533** [volcic/motom-toolbox#9]
Hi!
I tried to run "RUNME.m", but...

Error using loadlibrary
Failed to preprocess the input file.
 Output from preprocessor is:ndopto.h
e:\document\matlab\motom-toolbox-master\source\ndhost.h(134): fatal error C1189: #error:  NDI Error - Host not
defined. Options: PLATFORM_X86, PLATFORM_LINUX

Error in RUNME (line 107)
        [~, warnings] = loadlibrary('../bin/oapi.dll', '../source/ndopto.h', 'addheader', '../source/ndtypes.h',
        'addheader', '../source/ndhost.h', 'addheader', '../source/ndpack.h', 'mfilename','api_prototypes');

The version of the oapi is 3.05.01.0163, matlab is 2015b(32) and vs is 2015(32).
THANKS!

**Comment by ha5dzs** [comment]
Hi, Zoltan here.

It seems that your OAPI version is really old. Could you get a newer version? I don't think NDI will charge for that.
The latest OAPI I know is 3.15. It's worth getting it, as they fixed a few things, particularly rigid body management. Upgrading the OAPI for the toolbox will not cause incompatibilities with the old versions of installed applications, because it uses its own compiled binaries.

If you can't get the latest API, I think I still can help you, but we will enter uncharted territory.

**Comment by zhengyi0533** [comment]
I appreciate your help. I can't get the latest API in the near future. Could you tell me the OAPI you know whether hava “ndhost_int.h” file, or whether need this file? Because when I try to run this program, it shows that "#error: NDI Error - Host not
defined. "  Then I find the error's location in the hdhost.h file, and I post the relevent code here:

#ifdef NDI_INTERNAL_BUILD
#include <ndhost_int.h>
#else
#error NDI Error - Host not defined. Options: PLATFORM_X86, PLATFORM_LINUX
#endif

I can't find another NDI_INTERNAL_BUILD variable in all h files. And if the NDI_INTERNAL_BUILD is defined by adding #define NDI_INTERNAL_BUILD in the ndhost.h,  the program also can't run because of the lack of the ndhost_int.h.

And I also find it maybe need a borfix.h file. Some code of the ndhost.h file:

//--borland------------------------------------
#ifdef __BORLANDC__
#include <borfix.h>
#if defined( _NO_STDCALL )
#define NDI_DECL2
#else
#define NDI_DECL2       __stdcall
#endif  /* _NO_STDCALL */

Thanks! 
Yi Zheng

**Comment by ha5dzs** [comment]
Okay, this is going to be fun.

Answers sequentially:
>  Could you tell me the OAPI you know whether hava “ndhost_int.h” file

No, this is for NDI's internal build only. The only thing they did it to copy and paste a lot of things together and this is how they released the API. If you look at what functions are in the `.DLL` file, you will see that we users have access about 80-90% of the functions they use. Luckily we won't need the internal resource files to get this to work, so at least that saves a headache.

> And I also find it maybe need a `borfix.h` file.

If you decide to use the Borland C compiler, this will be in the default include path. I never tried to get it to work, as that compiler is really old. I am into vintage stuff for fun (I fix tube radios and VHS recorders, etc.), but not when I have to produce production-quality data that my career depends on. I think the last version of the Borland C compiler is from 1999 or so.


You are getting `NDI Error - Host not
defined. Options: PLATFORM_X86, PLATFORM_LINUX` the error in `ndhost.h` because the preprocessor fails to recognise your compiler. Due to platform differences, some variable types have to be defined in particular ways so that the same code would compile.
Since we know that the Visual Studio compiler is rather accommodating with these things, we can try just bypassing this check, and see if it works. I see that they also added some measures to handle some legacy NDI library calls for the Visual Studio compiler, but I don't think these matter with the API functions.

Could you add the line:
```
#define PLATFORM_X86
```
to the top of `ndhost.h` and try to compile it again?

**Comment by zhengyi0533** [comment]
Wow! It works! You're very professional！I don't know how to show you my gratitude, but I really appriciate of what you have done to me. Thank you very much!

**Comment by ha5dzs** [comment]
Well, it compiled, whether it works correctly is a different matter. I never used a library this old, and I know for a fact that NDI had fixed important bugs when they upgraded from OAPI 3.14 to 3.15. NDI gives out the upgrade for free, I think it's worth the upgrade. If you decide to use this old library, then proceed with caution and verify operation if possible.

If something doesn't work, feel free to open up a different issue, see if we can solve it. Oh, and please close this one, because I may get a free toaster for every five issues I help solve! :)
